name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout this repo
      uses: actions/checkout@v2
    -
      name: Checkout zigbee2mqtt repo
      uses: actions/checkout@v2
      with:
        repository: stas-demydiuk/domoticz-zigbee2mqtt-plugin
        path: zigbee2mqtt
    -
      name: Checkout xiaomi-roborock repo
      uses: actions/checkout@v2
      with:
        repository: mrin/domoticz-mirobot-plugin
        path: xiaomi-mirobot
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: stoorren/docker-domoticz:latest
    -
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
#    -
#      name: Update repo description
#      uses: peter-evans/dockerhub-description@v2
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_PASSWORD }}
#        repository: stoorren/docker-domoticz
